class Commands:
    LEECH = "subir"
    SETTINGS= "configuracion"
    EXEC = "exec"
    ABOUT = "info"
    GETLOGS = "logs"
    SERVER = "servidor"
    START = "start"
    SPEEDTEST = "test_velocidad"
    TEST= "test"
    CRLDATA = "limpiar"
