class Commands:
    LEECH = "upload"
    COPY = "copy"
    CONFIG= "config"
    EXEC = "exec"
    ABOUT = "info"
    GETLOGS = "logs"
    SERVER = "server"
    START = "start"
    SPEEDTEST = "speed_test"
    TEST= "test"
    CRLDATA = "cleardata"
    UPDATE= "update"
