class Commands:
    MIRROR = "mirror"
    LEECH= "leech"
    COPY = "copy"
    CONFIG= "config"
    MYFILES= "myfiles"
    EXEC = "exec"
    GETLOGS = "logs"
    SERVER = "server"
    START = "start"
    SPEEDTEST = "speedtest"
    TEST= "test"
    CRLDATA = "cleardata"
    RESTART= "restart"
