class Commands:
    START = "start"
    MIRROR = "mirror"
    MIRRORSET = "mirrorset"
    ZIPMIRROR = "zipmirror"
    UNZIPMIRROR = "unzipmirror"
    QBMIRROR= "qbmirror"
    LEECH= "leech"
    COPY = "copy"
    MYFILES= "myfiles"
    EXEC = "exec"
    GETLOGS = "logs"
    SERVER = "server"
    SPEEDTEST = "speedtest"
    RESTART= "restart"
    TEST= "test"
